name = "day01"
description = "Day 01 Advent of Code 2024"
version = "0.1.0-dev"

authors = ["Derek Kingston"]
maintainers = ["Derek Kingston <derek.kingston@gmail.com>"]
maintainers-logins = ["derekkingston"]
licenses = "MIT"
website = ""
tags = []

executables = ["day01"]

[[depends-on]]
gnatprove = "^14.1.1"
